#!/bin/env bash
# Installs the scripts and dotfiles to the current user.

# fix cwd problems
cd $(dirname $(readlink -f $0))

dest_xinitrc="$HOME/.xinitrc"
dest_vimrc="$HOME/.vimrc"
dest_comptonrc="$HOME/.config/compton.conf"
dest_bar="$HOME/.bar"

# backup xinitrc
[ -e "$dest_xinitrc" ] && cp "$dest_xinitrc" "$dest_xinitrc.backup"

# install xinitrc
ln -sf "$(realpath init)" "$dest_xinitrc"

# backup vimrc
[ -e "$dest_vimrc" ] && mv "$dest_vimrc" "$dest_vimrc.backup"

# install vimrc
ln -sf "$(realpath vim/vimrc)" "$dest_vimrc"

# install compton config
mkdir -p $HOME/.config
[ -e "$dest_comptonrc" ] && mv "$dest_comptonrc" "$dest_comptonrc.backup"
ln -s "$(realpath compton/compton.conf)" "$dest_comptonrc"

#install bar to home
[ -e "$dest_bar" ] && mv "$dest_bar" "$dest_bar.backup"
ln -s "$(realpath bar/startbar.sh)" "$dest_bar"
