#!/bin/env sh
# install helper

# check for applications
which zsh bash bspwm sxhkd feh xrdb xcompmgr polybar nvim vim tmux stow scrot google-chrome-stable i3lock-wrapper 1>/dev/null

if [ $? -ne 0 ]; then
    echo "Missing some programs. Please install them before proceeding."
    exit 1
fi

# check for fonts
if [[ $(fc-list | grep -i siji | wc -l) = 0 ]]; then
    echo "Missing siji font."
    exit 1
fi

if [[ $(fc-list | grep -i scientifica | wc -l) = 0 ]]; then
    echo "Missing boxxy font."
    exit 1
fi

for i in *; do
    [ -d "$i" ] && (echo "installing $i dotfiles" && stow -t $HOME $i)
done

# perform vim-plugged install
echo "installing vim plugins"
nvim +PlugInstall +q +q
