#!/bin/zsh
# WM init script
# This should execute first in .xinitrc

SXHKD_CONFIG=$HOME/config/sxhkd/sxhkdrc
BSPWM_CONFIG=$HOME/config/bspwm/bspwmrc
XRESOURCES=$HOME/config/xorg/xresources
WALLPAPER=$HOME/config/albumart/wallpaper.sh

sxhkd -c $SXHKD_CONFIG &

# Fix fonts
xset +fp "$HOME/.fonts"
xset fp rehash

xcompmgr -I 0.07 -O 0.07 &
xrdb -merge $XRESOURCES &
volnoti -t 1 &
$WALLPAPER &
bspwm -c $BSPWM_CONFIG
