#!/bin/env bash
# bspwm config

primary="DVI-D-0"
desktops_primary="m1 m2 m3 m4 m5 m6 m7 m8 m9 m10"
alternate="DVI-I-1"
desktops_alternate="a1 a2 a3 a4 a5 a6 a7 a8 a9 a10"

bspc config window_gap 16
bspc config border_width 0

bspc config -m $primary top_padding 40
bspc config -m $primary bottom_padding 40

bspc monitor $primary -d $desktops_primary
bspc monitor $alternate -d $desktops_alternate
