#!/bin/bash
# Initializes a primary monitor with some primary desktop and a secondary monitor with even more desktops.

DESKTOPS_MAIN="m1 m2 m3 m4 m5 m6 m7 m8 m9 m10"
DESKTOPS_EXT="e1 e2 e3 e4 e5 e6 e7 e8 e9 e10"

MONITOR_MAIN="DP-0"
MONITOR_EXT="DVI-I-1"

bspc config border_width 0
bspc config window_gap 2
bspc config -m $MONITOR_EXT top_padding 0

bspc monitor $MONITOR_MAIN -n b -d $DESKTOPS_MAIN
bspc monitor $MONITOR_EXT -n a -d $DESKTOPS_EXT
